server:
  port: 7110
  error:
    include-stacktrace: on_trace_param
spring:
  datasource:
    url: jdbc:postgresql://192.168.2.219:5432/db_ecommerce
    username: ecommerce
    password: ecommerce
  liquibase:
    change-log: classpath:db/db.changelog-master.xml
    enabled: true
    drop-first: false
    default-schema: sc_ecommerce_item
    database-change-log-table: ecommerce_item_changelog
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC